### ISSUE TITLE
[BUG]: Crash when trying to upload profile picture

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#77]
**Describe the bug**
App crashes when trying to upload a profile picture.

**To Reproduce**
1. Go through sign up flow
2. Click on (+) for uploading profile picture when prompted
3. Select select image source
4. App crashes

**Stack traces**
```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=69, result=0, data=null} to activity {org.collaction.collaction_app/org.collaction.collaction_app.MainActivity}: java.lang.IllegalStateException: Reply already submitted
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5114)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5155)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7851)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```
```
Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:14)
       at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.onActivityResult(ImageCropperDelegate.java:47)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:25)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:15)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:51)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:10)
       at android.app.Activity.dispatchActivityResult(Activity.java:8424)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5107)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5155)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7851)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

**Device information:**
 - Device: moto g(9) play
 - OS: Android 11
 - Version + build number: 1.0.1+252

**Comment by Xazin** [comment]
This seems to be caused by bad state management. I will try to reproduce tomorrow and let you know what I find.

**Comment by yasht01** [comment]
Hey, me and Saksham had look at this. We just had to add `<activity>` tag for allowing UCropActivity into the AndroidManifest.xml. 

[ImageCropper Docs](https://pub.dev/packages/image_cropper#how-to-install)

**Comment by Xazin** [comment]
@yasht01 will you create a PR with the fix?

**Comment by yasht01** [comment]
@Xazin Sure! I'll be working on uploading profile picture to the backend too. Will make a combined PR then
